### ISSUE TITLE
UI crashes when clearing selected parameter in result bar

### ISSUE THREAD

**Issue by neilsquinn** [DataKind-DC/CMC#31]
Select a station, then select a parameter in the sidebar, then click the Clear button, and the UI crashes.
`TypeError: Cannot read property 'value' of undefined`
Line 58 in index.js:
` MarkerMap = dynamic(() => import('../components/map'), {ssr: false});`

**Comment by danbernstein** [comment]
I am unable to reproduce this error. Does this happen with selecting any station or one specific station? Could you say any more about what error it throws?

**Comment by neilsquinn** [comment]
It was happening for any station - the `updateChartData` callback function was assuming there would be something selected, which wasn't the case if you clicked the Clear button. Filed above PR to look-before-leaping and reset `state.chart_data` to an empty array if the selection is empty.
